format = """
$battery\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$docker_context\
$container\
$cmake\
$java\
$golang\
$python\
$line_break\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character
"""

[hostname]
ssh_only = false
format = "@[$hostname]($style): "
style = "fg:#A3D740 bold"

[username]
style_user = "fg:#ED6839 bold"
format = "[$user]($style)"
disabled = false
show_always = true

[battery]
full_symbol = "full "
charging_symbol = "charging "
discharging_symbol = "discharging "
format = "battery [$symbol$percentage]($style) "

[[battery.display]]
threshold = 100
style = "white"

[[battery.display]]
threshold = 25
style = "bold red"

[directory]
truncation_length = 8
truncation_symbol = ".../"
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style) "

[memory_usage]
disabled = false
threshold = -1
format = " [$symbol]($style) [${ram}( swap ${swap})]($style)  "
symbol = "memory"
style = "bold dimmed green"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
symbol = "aws "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "cmake "

[dart]
symbol = "dart "

[deno]
symbol = "deno "

[dotnet]
symbol = ".NET "

[docker_context]
symbol = "docker "

[elixir]
symbol = "exs "

[elm]
symbol = "elm "

[git_branch]
symbol = "git "
style = "fg:#D038D8 bold"

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[julia]
symbol = "jl "

[kotlin]
symbol = "kt "

[nodejs]
symbol = "nodejs "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = "py "

[ruby]
symbol = "rb "

[rust]
symbol = "rs "

[scala]
symbol = "scala "

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "
